### ISSUE TITLE
Disabling paste into text boxes

### ISSUE THREAD

**Issue by maria-antoniak** [davidjurgens/potato#70]
It would be awesome if there was a built-in way to disable pasting text into specific text boxes, as this gives us one small defense against participants using chatbots to answer study questions.

**Comment by Jiaxin-Pei** [comment]
I just added this feature in [potato v1.2.1.4](https://github.com/davidjurgens/potato/commit/91ce7f1564feb1e48d3d1e42714602997f1a8624)

you could add the `allowing_paste` field and set it as `False`:

```YAML
"annotation_schemes": [      
        {
            "annotation_type": "text",
            "name": "textbox_input",
            "description": "How does this text make you feel?",
            # you could easily define a list of textboxes within one schema with a list of labels
            "labels": ['happy?','sad?'],
            # if you want to use multi-line textbox, turn on the text area and set the desired rows and cols of the textbox
            "textarea": {
              "on": False,
              "rows": 2,
              "cols": 40
            },
            "allowing_paste": False
        }       
    ],
```

This will disallow pasting into the textbox and will alert the user when they are pasting.

<img width="447" alt="image" src="https://github.com/davidjurgens/potato/assets/42936410/a9045b30-df85-4dd0-8efa-7455b6756e13">


Please upgrade `potato-annotation ` to use it.
