### ISSUE TITLE
Add ability to share login creditials between instances of Potato

### ISSUE THREAD

**Issue by davidjurgens** [davidjurgens/potato#8]

**Comment by davidjurgens** [comment]
This is now supported through multiple authentication backends:

**Database backend** — multiple Potato instances can share credentials by pointing at the same database:
```yaml
authentication:
  method: database
  database_url: postgresql://user:pass@shared-host/auth_db
```
Supports SQLite (single-machine) and PostgreSQL (multi-machine).

**OAuth backend** — delegates authentication to an external provider (Google, GitHub, etc.). All instances using the same OAuth provider share login implicitly.

**Clerk backend** — third-party SSO via Clerk API. All instances using the same Clerk application share credentials.

There's no built-in Potato-to-Potato auth federation, but the database and OAuth backends cover the practical use cases for sharing credentials across instances.

Closing as implemented.
